Repository xnelb013/chal-kak, pull requests merged in 2023-08, with the labels that each got.

#10 [Setting] : 초기 세팅
  .eslintrc.json
  .gitmessage
  .prettierrc
  package-lock.json
  package.json
  pages/_app.tsx
  pages/components/Navbar.tsx
  pages/index.tsx
  public/fonts/font.css
  public/fonts/notoSansKr.css
  public/images/카카오.jpg
  styles/globals.css
  tailwind.config.ts
Labels: Chore

#11 [Setting] : 초기 세팅
  .eslintrc.json
  .gitmessage
  .prettierrc
  package-lock.json
  package.json
  pages/_app.tsx
  pages/components/Navbar.tsx
  pages/index.tsx
  public/fonts/font.css
  public/fonts/notoSansKr.css
  public/images/카카오.jpg
  styles/globals.css
  tailwind.config.ts
Labels: Chore

#14 [Feat, Fix] : Navbar 추가, ESLint 수정
  .eslintrc.json
  .github/ISSUE_TEMPLATE/issue-template.md
  next.config.js
  pages/_document.tsx
  pages/components/Navbar.tsx
  postcss.config.js
Labels: Bug&Fix

#15 [Feat] : Navbar 완성
  .eslintrc.json
  .github/ISSUE_TEMPLATE/issue-template.md
  next.config.js
  pages/_document.tsx
  pages/components/Navbar.tsx
  postcss.config.js
Labels: Bug&Fix, Feat

#16 [Feat] : 회원가입 구현
  .eslintrc.json
  package-lock.json
  package.json
  pages/_document.tsx
  pages/signup/KeywordModal.tsx
  pages/signup/index.tsx
  public/images/keywordImages/댄디.png
  public/images/keywordImages/데이트룩.png
  public/images/keywordImages/미니멀.png
  public/images/keywordImages/비즈니스캐주얼.png
  public/images/keywordImages/빈티지.png
  public/images/keywordImages/스트릿.png
  public/images/keywordImages/스포티.png
  public/images/keywordImages/아메카지.png
  public/images/keywordImages/여행룩.png
  public/images/keywordImages/원마일웨어.png
  public/images/keywordImages/출근룩.png
  public/images/keywordImages/하객룩.png
  styles/globals.css
Labels: Feat

#17 [Feat] : 로그인 구현
  package-lock.json
  package.json
  pages/login/index.tsx
Labels: Feat
